In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [2]:
import os
import functools as ft
files = os.listdir('datasetIOT')
dfs=[]
for file in files:
    dftmp = pd.read_csv('datasetIOT'+'/'+file)
    dfs.append(dftmp.sample(n=50))
df_final = pd.concat(dfs)

In [3]:
data=df_final['ROAD_TYPE']
values=np.array(data)
print(data)
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
df_final['ROAD_TYPE']=onehot_encoded
data=df_final['POINT_1_STREET']
values=np.array(data)
print(data)
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
df_final['POINT_1_STREET']=onehot_encoded

1027    MAJOR_ROAD
2649    MAJOR_ROAD
2386    MAJOR_ROAD
2191    MAJOR_ROAD
4576    MAJOR_ROAD
           ...    
3782    MAJOR_ROAD
5300    MAJOR_ROAD
1870    MAJOR_ROAD
3871    MAJOR_ROAD
9160    MAJOR_ROAD
Name: ROAD_TYPE, Length: 25000, dtype: object
[0 0 0 ... 0 0 0]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
1027           Viborgvej
2649       Hasle Ringvej
2386           Viborgvej
2191     Edwin Rahrs Vej
4576       Ravnsbjergvej
              ...       
3782    Vejlby Centervej
5300      Skanderborgvej
1870            Grenåvej
3871           Viborgvej
9160        Silkeborgvej
Name: POINT_1_STREET, Length: 25000, dtype: object
[48  9 48 ...  7 48 33]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
result=df_final["vehicleCount"]
dataset=df_final.drop(labels=["Unnamed: 0.1","Unnamed: 0","POINT_2_STREET","POINT_1_CITY","event","POINT_2_CITY","vehicleCount","date"],axis=1)

In [5]:
df_final.corr().style.background_gradient(cmap='Blues')

In [6]:
result = np.where(df_final['vehicleCount']>=20,np.where(df_final['vehicleCount']>=50, 2,1), 0)

In [7]:
from sklearn import svm
from sklearn.model_selection import train_test_split
x_train, x_test, Y_train, Y_test = train_test_split(dataset, result, test_size = 0.3,random_state=5)
model = svm.SVC(kernel='linear').fit(x_train, Y_train)


In [ ]:
dudoan = model.predict(x_test)
print('R-Squared: %.4f' % model.score(x_test,Y_test))
print("coef",model.coef_)
print("intercept",model.intercept_)
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(Y_test, dudoan)
print('mse:',mse)

R-Squared: 0.6427
coef [[-5.72059483e+01  1.87595865e+01 -2.84574510e+01  6.91605470e+01
   2.23656641e+01 -6.01692054e+01 -1.32957138e+01 -1.91682158e+02
   1.00000000e+00  1.15646519e+00  1.06156584e+00 -6.16612747e-01
  -7.14965355e-02  3.10352132e+00 -7.89052498e+00  1.45365805e+02
   9.60852206e+00 -1.00000000e+00  3.11574191e-01 -1.05965927e+01]
 [ 3.26294899e+02  4.76291314e+00  3.00674047e+01  1.76779859e+02
  -1.28194091e+02 -4.36066509e+01  9.01140557e+00 -2.76975525e+02
   1.00000000e+00  1.21412050e+00  1.26164774e+00 -1.24959735e-01
  -7.57527822e-02  6.26188235e+00 -1.06589126e+00  3.03999511e+02
  -1.81844959e+02 -2.00000000e+00  4.88128051e-01 -1.35394494e+01]
 [ 3.51666533e+02 -2.09194229e+01  5.05345658e+01 -5.15585373e+01
  -1.40566717e+02  4.28148012e+01  1.60253049e+01 -6.72874992e+01
   0.00000000e+00  3.94810016e-01  6.37778853e-01  2.90725846e-01
   1.03270439e-01  5.39573752e+00  2.21433559e+00  5.74521021e+01
  -7.95957349e+01 -2.03478983e+00  1.65227443e-01 -

In [1]:
from sklearn import linear_model